### ISSUE TITLE
Show date/time for builds

### ISSUE THREAD

**Issue by ivankravets** [smartanthill/smartanthill-status#2]
Is difficult to show date/time instead (or alongside with) build number?

**Comment by dmytrokyrychuk** [comment]
No, it is not difficult.

Actually, as I recently discovered, log parser still has that few lines of code which are responsible for commit date parsing. So now I only need to:
- [x] add `committed_at` column to `BuildStatistics` model;
- [x] show commit time in table below memory usage charts.
